apiVersion: v1
kind: Service
metadata:
  name: orderflow
  namespace: orderflow-production
spec:
  selector:
    app.kubernetes.io/name: orderflow
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
